# Generated by Django 4.0.3 on 2022-05-06 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nombre',
            field=models.TextField(default='', max_length=60),
            preserve_default=False,
        ),
    ]
