# Generated by Django 4.0.3 on 2022-05-06 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='nombre',
            new_name='Nombre',
        ),
    ]
