# Generated by Django 4.0.3 on 2022-05-06 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_nombre_profile_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Nombre',
        ),
    ]
