# Generated by Django 4.0.3 on 2022-05-06 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudAdop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Edad', models.CharField(max_length=50)),
                ('Correo', models.EmailField(max_length=254)),
                ('Telefono', models.CharField(max_length=8)),
                ('Domicilio', models.CharField(max_length=100)),
                ('NumeroMasc', models.IntegerField()),
                ('Razones', models.CharField(max_length=150)),
                ('Estado', models.CharField(default='En proceso', max_length=15)),
            ],
        ),
    ]
