# Generated by Django 4.0.3 on 2022-05-06 04:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroMascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(default='default.jpg', upload_to='fotos_mascotas')),
                ('alimentacion', models.CharField(max_length=50)),
                ('vacunacion', models.CharField(max_length=100)),
                ('edad', models.CharField(max_length=30)),
                ('fecha_de_rescate', models.DateTimeField(default=django.utils.timezone.now)),
                ('raza', models.CharField(max_length=50)),
                ('enfermedades', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('adoptante', models.CharField(default='Disponible', max_length=50)),
            ],
        ),
    ]
