# Generated by Django 4.0.3 on 2022-05-11 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0002_rename_adoptante_registromascota_apellidoadoptante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registromascota',
            name='vacunacion',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
